export const sins = [
  "I bought at the top",
  "I changed my stop-loss 5 times",
  "I followed shady signal groups",
  "I filled the bag, no escape now",
  "I kept lowering my stop-level",
  "I traded against the trend",
  "I used insane leverage",
  "I was unaware of market timings",
  "I ignored the odds",
  "I bought without thinking",
  "It's definitely going to moon...",
  "I sold based on a signal guy's advice",
  "I tried to take revenge on the chart",
  "I went all-in on one coin",
  "I bought out of greed",
  "I bought the dip, and it dipped more",
  "Saw a pump, FOMO'd in",
  "I was late to short",
  "I didn’t even read the whitepaper",
  "I opened a trade because I felt like it",
];